# linreg algorithm - R implementation

## Baselining

### Part 0

```{r,echo=FALSE}
library(DiagrammeR)
diagram <- "
graph TB
subgraph linreg
A[raw sample]==>B[set baseline to <br/> minimum observation]
B==>C[apply baseline]
C==>D{check for amplification}
D== yes ==>Eyes[Determine SDM cycle (end of the e)]
D== no ==>Eno[skip sample]

style A fill:#DCEBE3
style B fill:#77DFC9
style C fill:#DEDBBA
style D fill:#77DFC9
style Eyes fill:#DEDBBA
style Eno fill:#DEDBBA
end

subgraph questions
A2[no questions]==>B2[no questions]
B2==>C2[Does apply baseline mean substract baseline? <br/> If the baseline is smaller than 0, should it be also substracted?]
C2==>D2[Samples are skipped when less than seven times <br/> increase in fluorescence values is observed]
D2== yes ==>Eyes2[Which algorithm was used for derivation?]
D2== no ==>Eno2[no questions]

style A2 fill:#DCEBE3
style B2 fill:#77DFC9
style C2 fill:#DEDBBA
style D2 fill:#77DFC9
style Eyes2 fill:#DEDBBA
style Eno2 fill:#DEDBBA
end
"

mermaid(diagram)
```

### Part I

```{r,echo=FALSE}

diagram <- "
graph TB
subgraph linreg
B[set baseline too high: <br/> baseline is the average of the 6th and the 7th point <br/> below the plateau phase]==>C[apply baseline]
C==>D{compare S-upper and S-lower}
D== S-upper > S-lower ==>Esmaller[Define step: 0.005*baseline]
D== S-upper < S-lower ==>Ebigger[Decrease baseline by 0.01]
Ebigger== S-upper < S-lower ==>F{baseline < min. observ}
F== no ==>C
F== yes ==>G[baseline error]


style B fill:#77DFC9
style C fill:#DEDBBA
style D fill:#77DFC9
style Ebigger fill:#DEDBBA
style Esmaller fill:#DEDBBA
style F fill:#77DFC9
style G fill:#DEDBBA
end

subgraph questions
B2[ANSWERED]==>C2[no questions]
C2==>D2[no questions]


style B2 fill:#77DFC9
style C2 fill:#DEDBBA
style D2 fill:#77DFC9
end
"

mermaid(diagram)
```